<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\Soso.Serialization\libs\Soso.Serialization\Soso.Serialization\Soso.Serialization.csproj" />
        <ProjectReference Include="..\..\..\..\Soso.Utils\libs\Soso.Utils\Soso.Utils\Soso.Utils.csproj" ExcludeAssets="runtime" Private="false"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="K4os.Compression.LZ4" Version="1.3.8" />
      <PackageReference Include="K4os.Compression.LZ4.Streams" Version="1.3.8" />
    </ItemGroup>

</Project>
